let livres = [
  {
    id_livre:1,
    titre: "Anna Karenine",
    categorie: "Roman realiste",
    nombre_de_pages: 864,
    extrait: "chemin/vers/anna_karenine.pdf",
    resume:
      "Le drame de ladultere dAnna Karenine, qui entraine des consequences tragiques dans la haute societe russe.",
    auteur: {
      nom: "Tolstoi",
      prenom: "Leon",
    },
    editeur: "The Russian Messenger",
    "annee_dedition": 1877,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/anna_karenine.jpg",
  },
  {
    id_livre:2,
    titre: "Le Proces",
    categorie: "Roman philosophique",
    nombre_de_pages: 304,
    extrait: "chemin/vers/le_proces.pdf",
    resume:
      "Joseph K. est accuse dun crime mysterieux et se retrouve pris dans un systeme judiciaire kafkaïen.",
    auteur: {
      nom: "Kafka",
      prenom: "Franz",
    },
    editeur: "Verlag Die Schmiede",
    "annee_dedition": 1925,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/le_proces.jpg",
  },
  {
    id_livre:3,
    titre: "Don Quichotte",
    categorie: "Roman satirique",
    nombre_de_pages: 1056,
    extrait: "chemin/vers/don_quichotte.pdf",
    resume:
      "Les aventures de Don Quichotte et de son fidele ecuyer Sancho Panza, qui parcourent lEspagne en quete didealisme.",
    auteur: {
      nom: "Cervantes",
      prenom: "Miguel de",
    },
    editeur: "Francisco de Robles",
    "annee_dedition": 1605,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/don_quichotte.jpg",
  },
  {
    id_livre:4,
    titre: "Le Comte de Monte-Cristo",
    categorie: "Roman daventure",
    nombre_de_pages: 1248,
    extrait: "chemin/vers/le_comte_de_monte_cristo.pdf",
    resume:
      "Edmond Dantes cherche vengeance apres avoir ete trahi et emprisonne a tort.",
    auteur: {
      nom: "Dumas",
      prenom: "Alexandre",
    },
    editeur: "Baudry",
    "annee_dedition": 1844,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/le_comte_de_monte_cristo.jpg",
  },
  {
    id_livre:5,
    titre: "Moby Dick",
    categorie: "Roman daventure",
    nombre_de_pages: 544,
    extrait: "chemin/vers/moby_dick.pdf",
    resume:
      "Lobsession du capitaine Achab pour traquer la baleine blanche, Moby Dick, a travers les oceans.",
    auteur: {
      nom: "Melville",
      prenom: "Herman",
    },
    editeur: "Harper & Brothers",
    "annee_dedition": 1851,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/moby_dick.jpg",
  },
  {
    id_livre:6,
    titre: "Les Hauts de Hurlevent",
    categorie: "Roman gothique",
    nombre_de_pages: 342,
    extrait: "chemin/vers/les_hauts_de_hurlevent.pdf",
    resume:
      "La passion destructrice entre Catherine Earnshaw et Heathcliff, dans les landes sauvages du Yorkshire.",
    auteur: {
      nom: "Bronte",
      prenom: "Emily",
    },
    editeur: "Thomas Cautley Newby",
    "annee_dedition": 1847,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/les_hauts_de_hurlevent.jpg",
  },
  {
    id_livre:7,
    titre: "LOdyssée",
    categorie: "Epopée, Mythe",
    nombre_de_pages: 384,
    extrait: "chemin/vers/l_odyssee.pdf",
    resume:
      "Les aventures dUlysse, roi dIthaque, lors de son long voyage de retour apres la guerre de Troie.",
    auteur: {
      nom: "Homere",
      prenom: "",
    },
    editeur: "Inconnu",
    "annee_dedition": -700,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/l_odyssee.jpg",
  },
  {
    id_livre:8,
    titre: "Les Trois Mousquetaires",
    categorie: "Roman daventure",
    nombre_de_pages: 640,
    extrait: "chemin/vers/les_trois_mousquetaires.pdf",
    resume:
      "Les aventures de dArtagnan et de ses amis, les mousquetaires du roi, dans la France du XVIIe siecle.",
    auteur: {
      nom: "Dumas",
      prenom: "Alexandre",
    },
    editeur: "Baudry",
    "annee_dedition": 1844,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/les_trois_mousquetaires.jpg",
  },
  {
    id_livre:9,
    titre: "Frankenstein",
    categorie: "Roman gothique, Science-fiction",
    nombre_de_pages: 280,
    extrait: "chemin/vers/frankenstein.pdf",
    resume:
      "Le scientifique Victor Frankenstein cree une creature monstrueuse qui echappe a son controle.",
    auteur: {
      nom: "Shelley",
      prenom: "Mary",
    },
    editeur: "Lackington, Hughes, Harding, Mavor & Jones",
    "annee_dedition": 1818,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/frankenstein.jpg",
  },
  {
    id_livre:10,
    titre: "Les Aventures de Tom Sawyer",
    categorie: "Roman dapprentissage",
    nombre_de_pages: 272,
    extrait: "chemin/vers/les_aventures_de_tom_sawyer.pdf",
    resume:
      "Les aventures de Tom Sawyer, un garcon espiegle, dans le Mississippi du XIXe siecle.",
    auteur: {
      nom: "Twain",
      prenom: "Mark",
    },
    editeur: "Chatto & Windus",
    "annee_dedition": 1876,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/les_aventures_de_tom_sawyer.jpg",
  },
  {
    id_livre:11,
    titre: "Les Quatre Filles du docteur March",
    categorie: "Roman de formation",
    nombre_de_pages: 528,
    extrait: "chemin/vers/les_quatre_filles_du_docteur_march.pdf",
    resume:
      "Les aventures et les epreuves des quatre soeurs March pendant la guerre de Secession.",
    auteur: {
      nom: "Alcott",
      prenom: "Louisa May",
    },
    editeur: "Roberts Brothers",
    "annee_dedition": 1868,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/les_quatre_filles_du_docteur_march.jpg",
  },
  {
    id_livre:12,
    titre: "Dracula",
    categorie: "Roman gothique, Horreur",
    nombre_de_pages: 418,
    extrait: "chemin/vers/dracula.pdf",
    resume:
      "Le compte terrifiant du vampire Dracula qui sinstalle en Angleterre pour semer le chaos.",
    auteur: {
      nom: "Stoker",
      prenom: "Bram",
    },
    editeur: "Archibald Constable and Company",
    "annee_dedition": 1897,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/dracula.jpg",
  },
  {
    id_livre:13,
    titre: "Vingt mille lieues sous les mers",
    categorie: "Roman daventure, Science-fiction",
    nombre_de_pages: 624,
    extrait: "chemin/vers/vingt_mille_lieues_sous_les_mers.pdf",
    resume:
      "Les aventures du professeur Aronnax a bord du sous-marin Nautilus, commande par le mysterieux capitaine Nemo.",
    auteur: {
      nom: "Verne",
      prenom: "Jules",
    },
    editeur: "Pierre-Jules Hetzel",
    "annee_dedition": 1870,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/vingt_mille_lieues_sous_les_mers.jpg",
  },
  {
    id_livre:14,
    titre: "Orgueil et Prejuges",
    categorie: "Roman romantique",
    nombre_de_pages: 435,
    extrait: "chemin/vers/orgueil_et_prejuges.pdf",
    resume:
      "Lhistoire damour entre Elizabeth Bennet et Mr. Darcy, confrontes a lorgueil et aux prejuges sociaux de lAngleterre du XIXe siecle.",
    auteur: {
      nom: "Austen",
      prenom: "Jane",
    },
    editeur: "T. Egerton, Whitehall",
    "annee_dedition": 1813,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/orgueil_et_prejuges.jpg",
  },
  {
    id_livre:15,
    titre: "Crime et Chatiment",
    categorie: "Roman psychologique",
    nombre_de_pages: 551,
    extrait: "chemin/vers/crime_et_chatiment.pdf",
    resume:
      "Les tourments mentaux de Raskolnikov apres avoir commis un meurtre, et sa quete de redemption.",
    auteur: {
      nom: "Dostoievski",
      prenom: "Fiodor",
    },
    editeur: "The Russian Messenger",
    "annee_dedition": 1866,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/crime_et_chatiment.jpg",
  },
  {
    id_livre:16,
    titre: "Les Miserables",
    categorie: "Roman historique",
    nombre_de_pages: 1900,
    extrait: "chemin/vers/les_miserables.pdf",
    resume:
      "Lhistoire de Jean Valjean, un ancien bagnard, et de ses rencontres avec dautres personnages dans la France du XIXe siecle.",
    auteur: {
      nom: "Hugo",
      prenom: "Victor",
    },
    editeur: "A. Lacroix, Verboeckhoven & Cie",
    "annee_dedition": 1862,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/les_miserables.jpg",
  },
  {
    id_livre:17,
    titre: "Les Voyages de Gulliver",
    categorie: "Roman daventure, Satire",
    nombre_de_pages: 372,
    extrait: "chemin/vers/les_voyages_de_gulliver.pdf",
    resume:
      "Les aventures de Lemuel Gulliver dans des terres etranges, peuplees de creatures fantastiques.",
    auteur: {
      nom: "Swift",
      prenom: "Jonathan",
    },
    editeur: "Benjamin Motte",
    "annee_dedition": 1726,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/les_voyages_de_gulliver.jpg",
  },
  {
    id_livre:18,
    titre: "La Lettre ecarlate",
    categorie: "Roman historique",
    nombre_de_pages: 238,
    extrait: "chemin/vers/la_lettre_ecarlate.pdf",
    resume:
      "Lhistoire dHester Prynne, une femme condamnee pour adultere dans la Puritanisme de la Nouvelle-Angleterre.",
    auteur: {
      nom: "Hawthorne",
      prenom: "Nathaniel",
    },
    editeur: "Ticknor, Reed & Fields",
    "annee_dedition": 1850,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/la_lettre_ecarlate.jpg",
  },
  {
    id_livre:19,
    titre: "Les Liaisons dangereuses",
    categorie: "Roman epistolaire",
    nombre_de_pages: 528,
    extrait: "chemin/vers/les_liaisons_dangereuses.pdf",
    resume:
      "Les intrigues et les manipulations des personnages aristocratiques dans la France pre-revolutionnaire.",
    auteur: {
      nom: "de Laclos",
      prenom: "Pierre Choderlos",
    },
    editeur: "Durand Neveu",
    "annee_dedition": 1782,
    "moyenne_dappreciation": null,
    commentaires: [],
    image_de_couverture: "chemin/vers/les_liaisons_dangereuses.jpg",
  },
];
export { livres };
